const en = {
 title:'Permanent campaigns', intro:'Keep your group and progress between game sessions.', live:'Quick session', campaigns:'Campaigns', signIn:'Sign in with Google', auth:'Sign in to create a campaign or accept an invitation.', name:'Campaign name', create:'Create campaign', inviteCode:'Campaign invitation', join:'Join campaign', hint:'Paste the 48-character invitation from your GM. This is different from a session code.', list:'My campaigns', empty:'No campaigns yet.', open:'Open', back:'All campaigns', gm:'Game Master', player:'Player', members:'Members', invite:'Create invitation', inviteHint:'One use · valid for 7 days. Creating a new invitation replaces the previous one.', copy:'Copy invitation', copied:'Copied', revoke:'Cancel invitation', start:'Start campaign session', connect:'Join active session', offline:'The GM has not started a session yet.', refresh:'Refresh', retry:'Retry', loading:'Loading…', error:'Could not complete the request. Try again.', active:'An active session is open. Return to it or leave it before opening another campaign.', return:'Return to session', leave:'Save and leave session', leavePlayer:'Leave session', expired:'The invitation is invalid or has expired. Ask the GM for a new one.', forbidden:'You do not have access to this campaign.', configure:'The campaign server is not configured.', signRequired:'Please sign in again.', noNetwork:'The server did not respond. Retry the same request.', busy:'Working…', settlements:'Settlements', saved:'Campaign membership is saved to your account.', sessionFailed:'The session could not connect. Try again.', copyFailed:'Copy failed. Select and copy the invitation below.', saveFailed:'Could not save the session. It is still open.'
};
const uk = {
 title:'Постійні кампанії',intro:'Зберігайте групу та прогрес між ігровими сесіями.',live:'Швидка сесія',campaigns:'Кампанії',signIn:'Увійти через Google',auth:'Увійдіть, щоб створити кампанію або прийняти запрошення.',name:'Назва кампанії',create:'Створити кампанію',inviteCode:'Запрошення до кампанії',join:'Приєднатися до кампанії',hint:'Вставте запрошення від ГМ із 48 символів. Воно відрізняється від коду сесії.',list:'Мої кампанії',empty:'Кампаній поки немає.',open:'Відкрити',back:'Усі кампанії',gm:'Майстер гри',player:'Гравець',members:'Учасники',invite:'Створити запрошення',inviteHint:'Одноразове · діє 7 днів. Нове запрошення замінює попереднє.',copy:'Копіювати запрошення',copied:'Скопійовано',revoke:'Скасувати запрошення',start:'Почати сесію кампанії',connect:'Увійти в активну сесію',offline:'ГМ ще не почав сесію.',refresh:'Оновити',retry:'Повторити',loading:'Завантаження…',error:'Не вдалося виконати запит. Спробуйте ще раз.',active:'У вас відкрита сесія. Поверніться до неї або вийдіть, щоб відкрити іншу кампанію.',return:'Повернутися до сесії',leave:'Зберегти й вийти із сесії',leavePlayer:'Вийти із сесії',expired:'Запрошення недійсне або прострочене. Попросіть нове у ГМ.',forbidden:'У вас немає доступу до цієї кампанії.',configure:'Сервер кампаній не налаштовано.',signRequired:'Увійдіть в акаунт повторно.',noNetwork:'Сервер не відповів. Повторіть цей самий запит.',busy:'Виконується…',settlements:'Поселення',saved:'Участь у кампанії збережена у вашому акаунті.',sessionFailed:'Не вдалося підключити сесію. Спробуйте ще раз.',copyFailed:'Не вдалося скопіювати. Виділіть запрошення нижче та скопіюйте його.',saveFailed:'Не вдалося зберегти сесію. Вона залишається відкритою.'
};
const ru = {...uk,title:'Постоянные кампании',intro:'Сохраняйте группу и прогресс между игровыми сессиями.',live:'Быстрая сессия',campaigns:'Кампании',signIn:'Войти через Google',auth:'Войдите, чтобы создать кампанию или принять приглашение.',name:'Название кампании',create:'Создать кампанию',inviteCode:'Приглашение в кампанию',join:'Присоединиться к кампании',hint:'Вставьте приглашение ГМ из 48 символов. Это не код сессии.',list:'Мои кампании',empty:'Кампаний пока нет.',open:'Открыть',back:'Все кампании',gm:'Мастер игры',player:'Игрок',members:'Участники',invite:'Создать приглашение',inviteHint:'Одноразовое · действует 7 дней. Новое приглашение заменяет предыдущее.',copy:'Копировать приглашение',copied:'Скопировано',revoke:'Отменить приглашение',start:'Начать сессию кампании',connect:'Войти в активную сессию',offline:'ГМ ещё не начал сессию.',refresh:'Обновить',retry:'Повторить',loading:'Загрузка…',saved:'Участие в кампании сохранено в вашем аккаунте.'};
const pl = {...en,title:'Stałe kampanie',intro:'Zachowaj drużynę i postępy między sesjami.',live:'Szybka sesja',campaigns:'Kampanie',signIn:'Zaloguj przez Google',name:'Nazwa kampanii',create:'Utwórz kampanię',inviteCode:'Zaproszenie do kampanii',join:'Dołącz do kampanii',list:'Moje kampanie',empty:'Nie masz jeszcze kampanii.',open:'Otwórz',back:'Wszystkie kampanie',gm:'Mistrz gry',player:'Gracz',members:'Uczestnicy',invite:'Utwórz zaproszenie',copy:'Kopiuj zaproszenie',copied:'Skopiowano',start:'Rozpocznij sesję kampanii',connect:'Dołącz do aktywnej sesji',refresh:'Odśwież'};
Object.assign(en, {deleteCampaign:'Delete campaign', deleteConfirm:'Delete “{name}” permanently? This removes the campaign, settlements and GM save for all members. Personal character sheets are kept. This cannot be undone.', deleteLeaveFirst:'Leave this campaign session before deleting it.'});
Object.assign(ru, {deleteCampaign:'Удалить кампанию', deleteConfirm:'Удалить «{name}» навсегда? Кампания, поселения и сохранение ГМ будут удалены для всех участников. Личные листы персонажей останутся. Отменить удаление нельзя.', deleteLeaveFirst:'Перед удалением выйди из сессии этой кампании.'});
Object.assign(uk, {deleteCampaign:'Видалити кампанію', deleteConfirm:'Видалити «{name}» назавжди? Кампанію, поселення та збереження ГМ буде видалено для всіх учасників. Особисті аркуші персонажів залишаться. Скасувати видалення неможливо.', deleteLeaveFirst:'Перед видаленням вийдіть із сесії цієї кампанії.'});
Object.assign(pl, {deleteCampaign:'Usuń kampanię', deleteConfirm:'Usunąć „{name}” na zawsze? Kampania, osady i zapis MG zostaną usunięte dla wszystkich uczestników. Osobiste karty postaci pozostaną. Tej operacji nie można cofnąć.', deleteLeaveFirst:'Przed usunięciem opuść sesję tej kampanii.'});
export const campaignCopy = language => ({en,uk,ru,pl}[String(language).slice(0,2)] || en);
