const COPY = {
  en: {
    shortScope: 'Offline in stage 1: assignments and building moves. Purchases still need the server.',
    title: 'Shared settlements', lobby: 'Campaign lobby', offline: 'Saved settlements', refresh: 'Refresh campaign list', back: 'Back to campaigns',
    saved: 'Saved on this device', syncing: 'Processing…', confirmed: 'Last synchronization', next: 'Next automatic attempt', never: 'Not synchronized yet',
    pending: 'Actions waiting to synchronize', sync: 'Synchronize now', export: 'Export backup', review: 'Synchronization results', conflict: 'Some local orders require review after synchronization.',
    scope: 'Stage 1: worker assignments and moving existing buildings can be saved offline. Construction, purchases and account changes still require the server. Pending orders take effect on the server when synchronized; this stage does not credit backdated work or production.',
    first: 'Open a campaign online once to save it on this device. A cached campaign list alone does not contain its settlements.',
    empty: 'No cached campaigns on this device.', open: 'Open', stored: 'Offline copy available', uncached: 'First load requires a connection', auth: 'Sign in to access this account’s saved campaigns.', signIn: 'Sign in with Google',
    persist: 'Request persistent storage', persisted: 'Persistent storage granted. Keep an exported backup too.', bestEffort: 'Persistent storage was not granted. Export a backup before clearing browser data.',
    queued: 'Queued', accepted: 'Accepted', rejected: 'Not applied', snapshot: 'Cached shared campaign — not a separate personal settlement.',
    errors: {
      OFFLINE: 'No connection. Available offline actions can still be saved on this device.', ONLINE_ACTION_REQUIRED: 'This action still requires a server connection in stage 1.',
      NO_OFFLINE_SNAPSHOT: 'There is no saved campaign snapshot. Load it online once.', LOCAL_STORAGE_UNAVAILABLE: 'Device storage is unavailable. No new action was reported as saved.', LOCAL_STORAGE_FULL: 'Device storage is full. Export a backup and free space.',
      LOCAL_STORAGE_BLOCKED: 'Close other application tabs to finish opening local storage.', LOCAL_SCHEMA_UNSUPPORTED: 'This save needs a compatible application version.',
      LOCAL_BUSY: 'Another tab is synchronizing this campaign. Try again shortly.', PENDING_CONFIRMATION: 'An online action is awaiting confirmation. Synchronize before making another change.',
      OUTBOX_FULL: 'The local action queue is full. Synchronize or export a backup.', SYNC_REQUIRED: 'Synchronize the existing queue before this action.',
      COMMAND_CONFLICT: 'Another player or a confirmed event changed this object. The order was not applied.', LOCAL_CONFLICT: 'A queued order no longer matches the cached object.',
      INVALID_SYNC_ACK: 'The server confirmation could not be validated. The queue was kept.', SYNC_SEQUENCE_CONFLICT: 'Queue sequence conflict. Keep the backup; do not erase the local queue.',
      AUTH_CHANGED: 'The signed-in account changed. Sign in to the original account to resume its queue.', SIGN_IN_REQUIRED: 'Sign in again to synchronize. The local queue is retained.',
      FORBIDDEN: 'Access was denied. Cached editing is blocked until access is verified.', DATABASE_QUOTA_EXCEEDED: 'Database quota reached. The local queue is safe; synchronization will retry later.',
      SERVER_UNAVAILABLE: 'Server unavailable. Pending actions remain on this device.', TASK_FINISHED: 'The construction task is no longer available.',
      INVALID_LEGACY_PENDING: 'The previous pending command could not be migrated. Its original save was preserved.',
    },
  },
  ru: {
    shortScope: 'Автономно на этапе 1: назначения и перемещение. Покупки пока требуют сервера.',
    title: 'Общие поселения', lobby: 'Лобби кампании', offline: 'Сохранённые поселения', refresh: 'Обновить список кампаний', back: 'Назад к кампаниям',
    saved: 'Сохранено на устройстве', syncing: 'Обработка…', confirmed: 'Последняя синхронизация', next: 'Следующая автоматическая попытка', never: 'Синхронизации ещё не было',
    pending: 'Действий ожидает отправки', sync: 'Синхронизировать сейчас', export: 'Экспорт резервной копии', review: 'Результаты синхронизации', conflict: 'Часть локальных приказов требует проверки после синхронизации.',
    scope: 'Этап 1: без связи сохраняются назначения рабочих и перемещение существующих зданий. Строительство, покупки и изменения аккаунта пока требуют сервера. Приказы вступают в силу на сервере при синхронизации; работа и производство задним числом на этом этапе не начисляются.',
    first: 'Один раз откройте кампанию онлайн, чтобы сохранить её на устройстве. Один лишь сохранённый список кампаний не содержит поселений.',
    empty: 'На этом устройстве ещё нет сохранённых кампаний.', open: 'Открыть', stored: 'Есть автономная копия', uncached: 'Первое открытие требует связи', auth: 'Войдите, чтобы открыть сохранённые кампании своего аккаунта.', signIn: 'Войти через Google',
    persist: 'Запросить постоянное хранение', persisted: 'Постоянное хранение разрешено. Также сохраняйте экспортную копию.', bestEffort: 'Постоянное хранение не разрешено. Экспортируйте копию перед очисткой данных браузера.',
    queued: 'В очереди', accepted: 'Принято', rejected: 'Не применено', snapshot: 'Сохранённая общая кампания — не отдельное личное поселение.',
    errors: {
      OFFLINE: 'Нет связи. Доступные автономные действия сохраняются на устройстве.', ONLINE_ACTION_REQUIRED: 'На первом этапе это действие ещё требует связи с сервером.',
      NO_OFFLINE_SNAPSHOT: 'Нет сохранённого снимка кампании. Сначала загрузите её онлайн.', LOCAL_STORAGE_UNAVAILABLE: 'Хранилище устройства недоступно. Новое действие не отмечено как сохранённое.', LOCAL_STORAGE_FULL: 'Хранилище устройства заполнено. Экспортируйте копию и освободите место.',
      LOCAL_STORAGE_BLOCKED: 'Закройте другие вкладки приложения для открытия хранилища.', LOCAL_SCHEMA_UNSUPPORTED: 'Для этого сохранения нужна совместимая версия приложения.',
      LOCAL_BUSY: 'Другая вкладка синхронизирует кампанию. Повторите немного позже.', PENDING_CONFIRMATION: 'Онлайн-команда ожидает подтверждения. Сначала выполните синхронизацию.',
      OUTBOX_FULL: 'Локальная очередь заполнена. Синхронизируйте или экспортируйте копию.', SYNC_REQUIRED: 'Перед этим действием синхронизируйте текущую очередь.',
      COMMAND_CONFLICT: 'Другой игрок или подтверждённое событие изменили объект. Приказ не применён.', LOCAL_CONFLICT: 'Приказ в очереди больше не соответствует сохранённому объекту.',
      INVALID_SYNC_ACK: 'Не удалось проверить подтверждение сервера. Очередь сохранена.', SYNC_SEQUENCE_CONFLICT: 'Конфликт последовательности команд. Экспортируйте копию; не удаляйте очередь.',
      AUTH_CHANGED: 'Аккаунт изменился. Для продолжения его очереди войдите в исходный аккаунт.', SIGN_IN_REQUIRED: 'Для синхронизации войдите повторно. Локальная очередь сохранена.',
      FORBIDDEN: 'Доступ запрещён. Редактирование заблокировано до проверки доступа.', DATABASE_QUOTA_EXCEEDED: 'Квота базы исчерпана. Очередь сохранена; синхронизация повторится позже.',
      SERVER_UNAVAILABLE: 'Сервер недоступен. Ожидающие действия остаются на устройстве.', TASK_FINISHED: 'Эта задача строительства больше недоступна.',
      INVALID_LEGACY_PENDING: 'Прежнюю ожидающую команду не удалось перенести. Исходное сохранение не удалено.',
    },
  },
  uk: {
    shortScope: 'Автономно на етапі 1: призначення й переміщення. Покупки поки потребують сервера.',
    title: 'Спільні поселення', lobby: 'Лобі кампанії', offline: 'Збережені поселення', refresh: 'Оновити список кампаній', back: 'Назад до кампаній',
    saved: 'Збережено на пристрої', syncing: 'Обробка…', confirmed: 'Остання синхронізація', next: 'Наступна автоматична спроба', never: 'Синхронізації ще не було',
    pending: 'Дій очікує на надсилання', sync: 'Синхронізувати зараз', export: 'Експорт резервної копії', review: 'Результати синхронізації', conflict: 'Частина локальних наказів потребує перевірки після синхронізації.',
    scope: 'Етап 1: без зв’язку зберігаються призначення робітників і переміщення наявних будівель. Будівництво, покупки й зміни облікового запису поки потребують сервера. Накази набувають чинності на сервері під час синхронізації; робота й виробництво заднім числом на цьому етапі не нараховуються.',
    first: 'Один раз відкрийте кампанію онлайн, щоб зберегти її на пристрої. Сам список кампаній не містить поселень.',
    empty: 'На цьому пристрої ще немає збережених кампаній.', open: 'Відкрити', stored: 'Є автономна копія', uncached: 'Перше відкриття потребує зв’язку', auth: 'Увійдіть, щоб відкрити збережені кампанії свого облікового запису.', signIn: 'Увійти через Google',
    persist: 'Запросити постійне зберігання', persisted: 'Постійне зберігання дозволено. Також зберігайте експортну копію.', bestEffort: 'Постійне зберігання не дозволено. Експортуйте копію перед очищенням даних браузера.',
    queued: 'У черзі', accepted: 'Прийнято', rejected: 'Не застосовано', snapshot: 'Збережена спільна кампанія — не окреме особисте поселення.',
    errors: {
      OFFLINE: 'Немає зв’язку. Доступні автономні дії зберігаються на пристрої.', ONLINE_ACTION_REQUIRED: 'На першому етапі ця дія ще потребує зв’язку із сервером.',
      NO_OFFLINE_SNAPSHOT: 'Немає збереженого знімка кампанії. Спочатку завантажте її онлайн.', LOCAL_STORAGE_UNAVAILABLE: 'Сховище пристрою недоступне. Нову дію не позначено як збережену.', LOCAL_STORAGE_FULL: 'Сховище пристрою заповнене. Експортуйте копію та звільніть місце.',
      LOCAL_STORAGE_BLOCKED: 'Закрийте інші вкладки застосунку для відкриття сховища.', LOCAL_SCHEMA_UNSUPPORTED: 'Для цього збереження потрібна сумісна версія застосунку.',
      LOCAL_BUSY: 'Інша вкладка синхронізує кампанію. Повторіть трохи пізніше.', PENDING_CONFIRMATION: 'Онлайн-команда очікує підтвердження. Спочатку виконайте синхронізацію.',
      OUTBOX_FULL: 'Локальна черга заповнена. Синхронізуйте або експортуйте копію.', SYNC_REQUIRED: 'Перед цією дією синхронізуйте поточну чергу.',
      COMMAND_CONFLICT: 'Інший гравець або підтверджена подія змінили об’єкт. Наказ не застосовано.', LOCAL_CONFLICT: 'Наказ у черзі більше не відповідає збереженому об’єкту.',
      INVALID_SYNC_ACK: 'Не вдалося перевірити підтвердження сервера. Чергу збережено.', SYNC_SEQUENCE_CONFLICT: 'Конфлікт послідовності команд. Експортуйте копію; не видаляйте чергу.',
      AUTH_CHANGED: 'Обліковий запис змінено. Щоб продовжити його чергу, увійдіть до початкового запису.', SIGN_IN_REQUIRED: 'Для синхронізації увійдіть повторно. Локальну чергу збережено.',
      FORBIDDEN: 'Доступ заборонено. Редагування заблоковано до перевірки доступу.', DATABASE_QUOTA_EXCEEDED: 'Квоту бази вичерпано. Чергу збережено; синхронізація повториться пізніше.',
      SERVER_UNAVAILABLE: 'Сервер недоступний. Дії, що очікують, залишаються на пристрої.', TASK_FINISHED: 'Це завдання будівництва більше недоступне.',
      INVALID_LEGACY_PENDING: 'Не вдалося перенести попередню команду. Початкове збереження не видалено.',
    },
  },
  pl: {
    shortScope: 'Offline w etapie 1: przydziały i przenoszenie. Zakupy nadal wymagają serwera.',
    title: 'Wspólne osady', lobby: 'Lobby kampanii', offline: 'Zapisane osady', refresh: 'Odśwież listę kampanii', back: 'Wróć do kampanii',
    saved: 'Zapisano na urządzeniu', syncing: 'Przetwarzanie…', confirmed: 'Ostatnia synchronizacja', next: 'Następna automatyczna próba', never: 'Jeszcze nie zsynchronizowano',
    pending: 'Działania oczekujące na wysłanie', sync: 'Synchronizuj teraz', export: 'Eksportuj kopię zapasową', review: 'Wyniki synchronizacji', conflict: 'Niektóre lokalne rozkazy wymagają sprawdzenia po synchronizacji.',
    scope: 'Etap 1: przydziały pracowników i przenoszenie istniejących budynków można zapisać offline. Budowa, zakupy i zmiany konta nadal wymagają serwera. Rozkazy obowiązują na serwerze od synchronizacji; ten etap nie nalicza pracy ani produkcji wstecz.',
    first: 'Otwórz kampanię online co najmniej raz, aby zapisać ją na urządzeniu. Sama lista kampanii nie zawiera osad.',
    empty: 'Brak zapisanych kampanii na tym urządzeniu.', open: 'Otwórz', stored: 'Kopia offline dostępna', uncached: 'Pierwsze otwarcie wymaga połączenia', auth: 'Zaloguj się, aby otworzyć zapisane kampanie tego konta.', signIn: 'Zaloguj przez Google',
    persist: 'Poproś o trwałe przechowywanie', persisted: 'Przyznano trwałe przechowywanie. Zachowuj także eksportowaną kopię.', bestEffort: 'Nie przyznano trwałego przechowywania. Eksportuj kopię przed usunięciem danych przeglądarki.',
    queued: 'W kolejce', accepted: 'Przyjęto', rejected: 'Nie zastosowano', snapshot: 'Zapisana wspólna kampania — nie osobna prywatna osada.',
    errors: {
      OFFLINE: 'Brak połączenia. Dostępne działania offline zapisują się na urządzeniu.', ONLINE_ACTION_REQUIRED: 'Na pierwszym etapie ta czynność nadal wymaga serwera.',
      NO_OFFLINE_SNAPSHOT: 'Brak zapisanego stanu kampanii. Najpierw otwórz ją online.', LOCAL_STORAGE_UNAVAILABLE: 'Pamięć urządzenia jest niedostępna. Nowego działania nie oznaczono jako zapisane.', LOCAL_STORAGE_FULL: 'Pamięć urządzenia jest pełna. Eksportuj kopię i zwolnij miejsce.',
      LOCAL_STORAGE_BLOCKED: 'Zamknij pozostałe karty aplikacji, aby otworzyć lokalną bazę.', LOCAL_SCHEMA_UNSUPPORTED: 'Ten zapis wymaga zgodnej wersji aplikacji.',
      LOCAL_BUSY: 'Inna karta synchronizuje kampanię. Spróbuj ponownie za chwilę.', PENDING_CONFIRMATION: 'Działanie online oczekuje na potwierdzenie. Najpierw zsynchronizuj.',
      OUTBOX_FULL: 'Lokalna kolejka jest pełna. Zsynchronizuj lub eksportuj kopię.', SYNC_REQUIRED: 'Najpierw zsynchronizuj istniejącą kolejkę.',
      COMMAND_CONFLICT: 'Inny gracz lub zatwierdzone zdarzenie zmieniło obiekt. Rozkazu nie zastosowano.', LOCAL_CONFLICT: 'Rozkaz w kolejce nie odpowiada już zapisanemu obiektowi.',
      INVALID_SYNC_ACK: 'Nie udało się sprawdzić potwierdzenia serwera. Kolejkę zachowano.', SYNC_SEQUENCE_CONFLICT: 'Konflikt kolejności poleceń. Eksportuj kopię; nie usuwaj kolejki.',
      AUTH_CHANGED: 'Konto zostało zmienione. Zaloguj się na poprzednie konto, aby kontynuować jego kolejkę.', SIGN_IN_REQUIRED: 'Zaloguj się ponownie, aby synchronizować. Kolejka lokalna pozostaje zapisana.',
      FORBIDDEN: 'Odmowa dostępu. Edycja zablokowana do weryfikacji uprawnień.', DATABASE_QUOTA_EXCEEDED: 'Wyczerpano limit bazy. Kolejka jest zapisana; synchronizacja ponowi próbę później.',
      SERVER_UNAVAILABLE: 'Serwer jest niedostępny. Oczekujące działania pozostają na urządzeniu.', TASK_FINISHED: 'To zadanie budowy jest już niedostępne.',
      INVALID_LEGACY_PENDING: 'Nie udało się przenieść poprzedniego polecenia. Oryginalny zapis zachowano.',
    },
  },
};
export function offlineCopy(language) { return COPY[String(language || 'en').split('-')[0]] || COPY.en; }
export function offlineError(code, language, fallback) { return offlineCopy(language).errors[code] || fallback || code; }
