const COPY = {
  en: { title:'Construction', workers:'Builders', building:'Under construction', waiting:'Waiting for builders', confirming:'Awaiting saved confirmation', eta:'Remaining', crew:'At the current crew size', estimate:'Live estimate. Completion is confirmed by the saved settlement state.', site:'Site and materials', frame:'Structure', finishing:'Finishing', complete:'Building completed', roomComplete:'Room completed', upgradeComplete:'Upgrade completed', open:'Open building', dismiss:'Dismiss notification', assign:'Assign a builder', needsWorker:'Worker needed', startWork:'Assign a worker', ready:'Ready for operation', automatic:'Automatic operation', unavailable:'Workplace unavailable', next:'Freed builders follow the existing construction queue.', minute:'min', hour:'h', day:'d', multiple:'Construction tasks' },
  ru: { title:'Строительство', workers:'Строители', building:'Строится', waiting:'Ожидает рабочих', confirming:'Ожидает подтверждения сохранения', eta:'Осталось', crew:'При текущем числе рабочих', estimate:'Текущий прогноз. Завершение подтверждается сохранённым состоянием поселения.', site:'Площадка и материалы', frame:'Возведение', finishing:'Завершающие работы', complete:'Здание построено', roomComplete:'Комната построена', upgradeComplete:'Улучшение завершено', open:'Открыть здание', dismiss:'Закрыть уведомление', assign:'Назначить строителя', needsWorker:'Нужен работник', startWork:'Назначить работника', ready:'Готово к работе', automatic:'Работает автоматически', unavailable:'Место работы недоступно', next:'Освободившиеся строители переходят по существующей очереди.', minute:'мин', hour:'ч', day:'д', multiple:'Задачи строительства' },
  uk: { title:'Будівництво', workers:'Будівельники', building:'Будується', waiting:'Очікує на працівників', confirming:'Очікує підтвердження збереження', eta:'Залишилося', crew:'За поточної кількості працівників', estimate:'Поточний прогноз. Завершення підтверджується збереженим станом поселення.', site:'Майданчик і матеріали', frame:'Зведення', finishing:'Завершальні роботи', complete:'Будівлю збудовано', roomComplete:'Кімнату збудовано', upgradeComplete:'Покращення завершено', open:'Відкрити будівлю', dismiss:'Закрити сповіщення', assign:'Призначити будівельника', needsWorker:'Потрібен працівник', startWork:'Призначити працівника', ready:'Готово до роботи', automatic:'Працює автоматично', unavailable:'Місце роботи недоступне', next:'Вільні будівельники переходять за наявною чергою.', minute:'хв', hour:'год', day:'д', multiple:'Завдання будівництва' },
  pl: { title:'Budowa', workers:'Budowniczowie', building:'W budowie', waiting:'Czeka na pracowników', confirming:'Oczekuje na potwierdzenie zapisu', eta:'Pozostało', crew:'Przy obecnej liczbie pracowników', estimate:'Bieżąca prognoza. Zakończenie potwierdza zapisany stan osady.', site:'Plac i materiały', frame:'Wznoszenie', finishing:'Prace wykończeniowe', complete:'Budynek ukończony', roomComplete:'Pomieszczenie ukończone', upgradeComplete:'Ulepszenie ukończone', open:'Otwórz budynek', dismiss:'Zamknij powiadomienie', assign:'Przydziel budowniczego', needsWorker:'Potrzebny pracownik', startWork:'Przydziel pracownika', ready:'Gotowe do pracy', automatic:'Praca automatyczna', unavailable:'Miejsce pracy niedostępne', next:'Wolni budowniczowie przechodzą do istniejącej kolejki.', minute:'min', hour:'godz', day:'d', multiple:'Zadania budowlane' },
};
export const constructionCopy = language => COPY[String(language || 'en').split('-')[0]] || COPY.en;
export function constructionDuration(ms, language) {
  if (!Number.isFinite(ms) || ms < 0) return '—';
  const text = constructionCopy(language), minutes = Math.max(1, Math.ceil(ms / 60000));
  const days = Math.floor(minutes / 1440), hours = Math.floor((minutes % 1440) / 60);
  if (days) return `${days} ${text.day} ${hours} ${text.hour}`;
  if (hours) return `${hours} ${text.hour} ${minutes % 60} ${text.minute}`;
  return `${minutes} ${text.minute}`;
}
