import * as V5 from "./proceduralRoomContentV5.js";
import { summarizeEncounter } from "./proceduralEncounterBalance.js";
import { SETTLEMENT_HOUSE_RULES } from "./proceduralSettlement.js";
import {
  generateProceduralWastelandPoiData,
  generateLocalizedProceduralWastelandPois,
} from "./proceduralWastelandPoi.js";

function isWasteland(spec = {}) {
  return String(spec?.type || "wasteland") === "wasteland";
}

function isSettlement(spec = {}) {
  return String(spec?.type || "") === "settlement";
}

function hash(value) {
  const text = String(value || "");
  let result = 2166136261;
  for (let index = 0; index < text.length; index += 1) {
    result ^= text.charCodeAt(index);
    result = Math.imul(result, 16777619);
  }
  return result >>> 0;
}

const FRIENDLY_GROUPS = {
  npc: ["Wastelander"],
  settler: ["Wastelander"],
  factionless: ["Wastelander"],
  wastelander: ["Wastelander"],
  minuteman: ["Minuteman"],
};

const HOSTILE_GROUPS = {
  raider: ["Raider", "Raider Scavver", "Raider Psycho", "Raider Veteran"],
  super_mutant: ["Super Mutant", "Super Mutant Brute", "Super Mutant Master", "Mutant Hound"],
};

function allowedGroups(room = {}) {
  const fromRoom = Array.isArray(room.allowedGroups) ? room.allowedGroups.filter(Boolean) : [];
  if (fromRoom.length) return fromRoom;
  return [...(SETTLEMENT_HOUSE_RULES[room.houseType]?.allowedGroups || [])];
}

function deterministicGroup(spec, room, groups, suffix) {
  if (!groups.length) return "";
  return groups[hash(`${spec.seed}:${room.houseId}:${suffix}`) % groups.length];
}

function settlementRoomRules(spec, rooms) {
  return rooms.map((room) => {
    const rule = SETTLEMENT_HOUSE_RULES[room.houseType];
    if (!rule) return room;

    const groups = allowedGroups(room);

    if (room.houseType === "ruined") {
      // Ruined homes intentionally keep the base encounter untouched: any
      // hostile group generated by the encounter system is legal here.
      return {
        ...room,
        disposition: "hostile",
        allowedGroups: ["any"],
        encounterMode: rule.encounterMode,
        lootProfile: "ruined",
      };
    }

    if (room.houseType === "civilian") {
      const available = groups.filter((group) => FRIENDLY_GROUPS[group]);
      const group = deterministicGroup(spec, room, available, "residents") || "wastelander";
      const candidates = FRIENDLY_GROUPS[group] || FRIENDLY_GROUPS.wastelander;
      const residents = room.baseRoomId === "living_room"
        ? [{
            type: candidates[0],
            count: 1,
            candidates: [...candidates],
            enemyGroup: group,
            disposition: "friendly",
            rank: "standard",
          }]
        : [];

      return {
        ...room,
        enemies: [],
        enemyGroup: "",
        residents,
        disposition: "friendly",
        allowedGroups: [...groups],
        encounterMode: rule.encounterMode,
        lootProfile: "civilian",
      };
    }

    if (room.houseType === "raider") {
      const available = groups.filter((group) => HOSTILE_GROUPS[group]);
      const group = deterministicGroup(spec, room, available, "hostiles") || "raider";
      const candidates = HOSTILE_GROUPS[group] || HOSTILE_GROUPS.raider;
      const enemies = (room.enemies || []).map((enemy, index) => ({
        ...enemy,
        type: candidates[index % candidates.length],
        candidates: [...candidates],
        enemyGroup: group,
        disposition: "hostile",
      }));

      return {
        ...room,
        enemies,
        enemyGroup: enemies.length ? group : "",
        disposition: "hostile",
        allowedGroups: [...groups],
        encounterMode: rule.encounterMode,
        lootProfile: "raider",
      };
    }

    return room;
  });
}

export function generateProceduralRoomData(spec = {}) {
  if (isWasteland(spec)) return generateProceduralWastelandPoiData(spec);
  const rooms = V5.generateProceduralRoomData(spec);
  return isSettlement(spec) ? settlementRoomRules(spec, rooms) : rooms;
}

export function generateProceduralEncounterSummary(spec = {}) {
  const data = generateProceduralRoomData(spec);
  return summarizeEncounter(spec, data);
}

export function roomDataById(data = [], id) {
  return V5.roomDataById(data, id);
}

export function roomPrimaryMarker(roomData) {
  return V5.roomPrimaryMarker(roomData);
}

export function localizeProceduralRoomData(data = [], lang = "en") {
  return V5.localizeProceduralRoomData(data, lang);
}

export function generateLocalizedProceduralRooms(spec = {}, lang = "en") {
  if (isWasteland(spec)) return generateLocalizedProceduralWastelandPois(spec, lang);
  return V5.localizeProceduralRoomData(generateProceduralRoomData(spec), lang);
}

export const LOOT_RARITIES = V5.LOOT_RARITIES;
export const WEALTH_LEVELS = V5.WEALTH_LEVELS;
export const normalizeLootRarity = V5.normalizeLootRarity;
