import * as V5 from "./proceduralRoomContentV5.js";
import { summarizeEncounter } from "./proceduralEncounterBalance.js";
import {
  generateProceduralWastelandPoiData,
  generateLocalizedProceduralWastelandPois,
} from "./proceduralWastelandPoi.js";

function isWasteland(spec = {}) {
  return String(spec?.type || "wasteland") === "wasteland";
}

function isSettlement(spec = {}) {
  return String(spec?.type || "") === "settlement";
}

/**
 * Settlement house type is visual-only.
 *
 * Enemy composition is generated by the common encounter pipeline from the
 * scene settings (enemyFaction, difficulty, party level/size, seed). Civilian,
 * ruined and raider house sprites no longer replace, remove or restrict the
 * enemies generated for a room.
 */
function unrestrictedSettlementRooms(rooms = []) {
  return rooms.map((room) => ({
    ...room,
    allowedGroups: ["any"],
    encounterMode: "unrestricted",
    disposition: (room?.enemies || []).some((enemy) => Number(enemy?.count || 0) > 0)
      ? "hostile"
      : "",
    residents: [],
  }));
}

export function generateProceduralRoomData(spec = {}) {
  if (isWasteland(spec)) return generateProceduralWastelandPoiData(spec);
  const rooms = V5.generateProceduralRoomData(spec);
  return isSettlement(spec) ? unrestrictedSettlementRooms(rooms) : rooms;
}

export function generateProceduralEncounterSummary(spec = {}) {
  const data = generateProceduralRoomData(spec);
  return summarizeEncounter(spec, data);
}

export function roomDataById(data = [], id) {
  return V5.roomDataById(data, id);
}

export function roomPrimaryMarker(roomData) {
  return V5.roomPrimaryMarker(roomData);
}

export function localizeProceduralRoomData(data = [], lang = "en") {
  return V5.localizeProceduralRoomData(data, lang);
}

export function generateLocalizedProceduralRooms(spec = {}, lang = "en") {
  if (isWasteland(spec)) return generateLocalizedProceduralWastelandPois(spec, lang);
  return V5.localizeProceduralRoomData(generateProceduralRoomData(spec), lang);
}

export const LOOT_RARITIES = V5.LOOT_RARITIES;
export const WEALTH_LEVELS = V5.WEALTH_LEVELS;
export const normalizeLootRarity = V5.normalizeLootRarity;
