const NAME_TERMS = {
  ru: {
    "Electric Signal Carrier Antennae": "Антенны электрического сигнала",
    "Gyro Compensating Lens": "Гирокомпенсирующая линза",
    "Recoil Compensating Stock": "Приклад с компенсацией отдачи",
    "Large Quick-Eject Mag": "Большой быстросъёмный магазин",
    "Short Night Vision Scope": "Короткий прицел ночного видения",
    "Long Night Vision Scope": "Длинный прицел ночного видения",
    "Electrified Serrated Blade": "Электрифицированный зазубренный клинок",
    "Bracketed Short Barrel": "Короткий ствол с креплением",
    "Bracketed Long Barrel": "Длинный ствол с креплением",
    "Vaporization Nozzle": "Испаряющее сопло",
    "Compression Nozzle": "Компрессионное сопло",
    "Electrification Module": "Модуль электрификации",
    "Ignition Module": "Модуль зажигания",
    "Targeting Computer": "Баллистический вычислитель",
    "Three-crank capacitor": "Трёхзарядный конденсатор",
    "Four-crank capacitor": "Четырёхзарядный конденсатор",
    "Five-crank capacitor": "Пятизарядный конденсатор",
    "Six-crank capacitor": "Шестизарядный конденсатор",
    "Sharpshooter’s Grip": "Снайперская рукоять",
    "Marksman’s Stock": "Снайперский приклад",
    "Automatic Piston": "Автоматический поршень",
    "Quick-Eject Mag": "Быстросъёмный магазин",
    "Large Magazine": "Большой магазин",
    "Photon Agitator": "Фотонный агитатор",
    "Photon Exciter": "Фотонный возбудитель",
    "Boosted Capacitor": "Усиленный конденсатор",
    "Beta Wave Tuner": "Настройщик бета-волн",
    "Charging Barrels": "Зарядные стволы",
    "Accelerated Barrel": "Ускоренный ствол",
    "Automatic Barrel": "Автоматический ствол",
    "Improved Barrel": "Улучшенный ствол",
    "Sniper Barrel": "Снайперский ствол",
    "Flamer Barrel": "Огнемётный ствол",
    "Long Barrel": "Длинный ствол",
    "Bull Barrel": "Утяжелённый ствол",
    "Shielded Barrel": "Экранированный ствол",
    "Reflex Sight": "Рефлекторный прицел",
    "Gunner Sight": "Стрелковый прицел",
    "Recon Scope": "Разведывательный прицел",
    "Short Scope": "Короткий прицел",
    "Long Scope": "Длинный прицел",
    "Night Vision Scope": "Прицел ночного видения",
    "Beam Splitter": "Расщепитель луча",
    "Beam Focuser": "Фокусировщик луча",
    "Muzzle Brake": "Дульный тормоз",
    "Signal Repeater": "Повторитель сигнала",
    "Comfort Grip": "Удобная рукоять",
    "Standard Stock": "Стандартный приклад",
    "Full Stock": "Полный приклад",
    "Serrated Blade": "Зазубренный клинок",
    "Electrified Blade": "Электрифицированный клинок",
    "Stealth Blade": "Скрытный клинок",
    "Curved Blade": "Изогнутый клинок",
    "Extended Blade": "Удлинённый клинок",
    "Extra Flame Jets": "Дополнительные форсунки пламени",
    "Heating Coil": "Нагревательная спираль",
    "Lead Lining": "Свинцовая накладка",
    "Extra Claw": "Дополнительный коготь",
    "Stun Pack": "Шоковый модуль",
    "Deep Dish": "Глубокая тарелка",
    "Large Tank": "Большой бак",
    "Huge Tank": "Огромный бак",
    "Triple Barrel": "Тройной ствол",
    "Quad Barrel": "Четверной ствол",
    "Tri-Barrel": "Трёхствольный блок",
    "Hair Trigger": "Чувствительный спуск",
    "Sawed-Off": "Обрезанный ствол",
    "Compensator": "Компенсатор",
    "Suppressor": "Глушитель",
    "Bayonet": "Штык",
    "Stabilizer": "Стабилизатор",
    "Hardened": "Закалённый",
    "Powerful": "Мощный",
    "Advanced": "Улучшенный",
    "Calibrated": "Калиброванный",
    "Automatic": "Автоматический",
    "Snubnose": "Короткий ствол",
    "Ported": "Портированный",
    "Vented": "Вентилируемый",
    "Finned": "Оребрённый",
    "Splitter": "Расщепитель",
    "Napalm": "Напалм",
    "Shredder": "Измельчитель",
    "Scope": "Оптический прицел",
    "Barbed": "С шипами",
    "Spiked": "Шипованный",
    "Sharp": "Заострённый",
    "Chain-Wrapped": "Обмотанный цепью",
    "Bladed": "С лезвием",
    "Puncturing": "Пробивающий",
    "Extra Heavy": "Сверхтяжёлый",
    "Heavy": "Тяжёлый",
    "Hooked": "С крюком",
    "Electrified": "Электрифицированный",
  },
  uk: {
    "Electric Signal Carrier Antennae": "Антени електричного сигналу",
    "Gyro Compensating Lens": "Гірокомпенсувальна лінза",
    "Recoil Compensating Stock": "Приклад із компенсацією віддачі",
    "Large Quick-Eject Mag": "Великий швидкознімний магазин",
    "Short Night Vision Scope": "Короткий приціл нічного бачення",
    "Long Night Vision Scope": "Довгий приціл нічного бачення",
    "Electrified Serrated Blade": "Електрифікований зазубрений клинок",
    "Bracketed Short Barrel": "Короткий ствол із кріпленням",
    "Bracketed Long Barrel": "Довгий ствол із кріпленням",
    "Vaporization Nozzle": "Випарне сопло",
    "Compression Nozzle": "Компресійне сопло",
    "Electrification Module": "Модуль електрифікації",
    "Ignition Module": "Модуль запалювання",
    "Targeting Computer": "Балістичний обчислювач",
    "Three-crank capacitor": "Трьохзарядний конденсатор",
    "Four-crank capacitor": "Чотирьохзарядний конденсатор",
    "Five-crank capacitor": "П’ятизарядний конденсатор",
    "Six-crank capacitor": "Шестизарядний конденсатор",
    "Sharpshooter’s Grip": "Снайперське руків’я",
    "Marksman’s Stock": "Снайперський приклад",
    "Automatic Piston": "Автоматичний поршень",
    "Quick-Eject Mag": "Швидкознімний магазин",
    "Large Magazine": "Великий магазин",
    "Photon Agitator": "Фотонний агітатор",
    "Photon Exciter": "Фотонний збуджувач",
    "Boosted Capacitor": "Посилений конденсатор",
    "Beta Wave Tuner": "Налаштовувач бета-хвиль",
    "Charging Barrels": "Зарядні стволи",
    "Accelerated Barrel": "Прискорений ствол",
    "Automatic Barrel": "Автоматичний ствол",
    "Improved Barrel": "Покращений ствол",
    "Sniper Barrel": "Снайперський ствол",
    "Flamer Barrel": "Вогнеметний ствол",
    "Long Barrel": "Довгий ствол",
    "Bull Barrel": "Обтяжений ствол",
    "Shielded Barrel": "Екранований ствол",
    "Reflex Sight": "Рефлекторний приціл",
    "Gunner Sight": "Стрілецький приціл",
    "Recon Scope": "Розвідувальний приціл",
    "Short Scope": "Короткий приціл",
    "Long Scope": "Довгий приціл",
    "Night Vision Scope": "Приціл нічного бачення",
    "Beam Splitter": "Розщеплювач променя",
    "Beam Focuser": "Фокусувальник променя",
    "Muzzle Brake": "Дульне гальмо",
    "Signal Repeater": "Повторювач сигналу",
    "Comfort Grip": "Зручне руків’я",
    "Standard Stock": "Стандартний приклад",
    "Full Stock": "Повний приклад",
    "Serrated Blade": "Зазубрений клинок",
    "Electrified Blade": "Електрифікований клинок",
    "Stealth Blade": "Прихований клинок",
    "Curved Blade": "Вигнутий клинок",
    "Extended Blade": "Подовжений клинок",
    "Extra Flame Jets": "Додаткові форсунки полум’я",
    "Heating Coil": "Нагрівальна спіраль",
    "Lead Lining": "Свинцева накладка",
    "Extra Claw": "Додатковий кіготь",
    "Stun Pack": "Шоковий модуль",
    "Deep Dish": "Глибока тарілка",
    "Large Tank": "Великий бак",
    "Huge Tank": "Величезний бак",
    "Triple Barrel": "Потрійний ствол",
    "Quad Barrel": "Четверний ствол",
    "Tri-Barrel": "Триствольний блок",
    "Hair Trigger": "Чутливий спуск",
    "Sawed-Off": "Обрізаний ствол",
    "Compensator": "Компенсатор",
    "Suppressor": "Глушник",
    "Bayonet": "Багнет",
    "Stabilizer": "Стабілізатор",
    "Hardened": "Загартований",
    "Powerful": "Потужний",
    "Advanced": "Удосконалений",
    "Calibrated": "Калібрований",
    "Automatic": "Автоматичний",
    "Snubnose": "Короткий ствол",
    "Ported": "Портований",
    "Vented": "Вентильований",
    "Finned": "Оребрений",
    "Splitter": "Розщеплювач",
    "Napalm": "Напалм",
    "Shredder": "Подрібнювач",
    "Scope": "Оптичний приціл",
    "Barbed": "З колючками",
    "Spiked": "Шипований",
    "Sharp": "Загострений",
    "Chain-Wrapped": "Обмотаний ланцюгом",
    "Bladed": "З лезом",
    "Puncturing": "Пробивний",
    "Extra Heavy": "Надважкий",
    "Heavy": "Важкий",
    "Hooked": "З гаком",
    "Electrified": "Електрифікований",
  },
  pl: {
    "Electric Signal Carrier Antennae": "Anteny sygnału elektrycznego",
    "Gyro Compensating Lens": "Soczewka żyrokompensacyjna",
    "Recoil Compensating Stock": "Kolba kompensująca odrzut",
    "Large Quick-Eject Mag": "Duży magazynek szybkowymienny",
    "Short Night Vision Scope": "Krótka luneta noktowizyjna",
    "Long Night Vision Scope": "Długa luneta noktowizyjna",
    "Electrified Serrated Blade": "Naelektryzowane ząbkowane ostrze",
    "Bracketed Short Barrel": "Krótka lufa z mocowaniem",
    "Bracketed Long Barrel": "Długa lufa z mocowaniem",
    "Vaporization Nozzle": "Dysza odparowująca",
    "Compression Nozzle": "Dysza kompresyjna",
    "Electrification Module": "Moduł elektryfikacji",
    "Ignition Module": "Moduł zapłonowy",
    "Targeting Computer": "Komputer celowniczy",
    "Three-crank capacitor": "Kondensator trójładunkowy",
    "Four-crank capacitor": "Kondensator czteroładunkowy",
    "Five-crank capacitor": "Kondensator pięcioładunkowy",
    "Six-crank capacitor": "Kondensator sześcioładunkowy",
    "Sharpshooter’s Grip": "Chwyt strzelecki",
    "Marksman’s Stock": "Kolba strzelecka",
    "Automatic Piston": "Tłok automatyczny",
    "Quick-Eject Mag": "Magazynek szybkowymienny",
    "Large Magazine": "Duży magazynek",
    "Photon Agitator": "Agitator fotonowy",
    "Photon Exciter": "Wzbudnik fotonowy",
    "Boosted Capacitor": "Wzmocniony kondensator",
    "Beta Wave Tuner": "Stroik fal beta",
    "Charging Barrels": "Lufy ładujące",
    "Accelerated Barrel": "Przyspieszona lufa",
    "Automatic Barrel": "Lufa automatyczna",
    "Improved Barrel": "Ulepszona lufa",
    "Sniper Barrel": "Lufa snajperska",
    "Flamer Barrel": "Lufa miotacza ognia",
    "Long Barrel": "Długa lufa",
    "Bull Barrel": "Ciężka lufa",
    "Shielded Barrel": "Osłonięta lufa",
    "Reflex Sight": "Celownik refleksyjny",
    "Gunner Sight": "Celownik strzelecki",
    "Recon Scope": "Luneta zwiadowcza",
    "Short Scope": "Krótka luneta",
    "Long Scope": "Długa luneta",
    "Night Vision Scope": "Luneta noktowizyjna",
    "Beam Splitter": "Rozdzielacz wiązki",
    "Beam Focuser": "Ogniskownik wiązki",
    "Muzzle Brake": "Hamulec wylotowy",
    "Signal Repeater": "Wzmacniacz sygnału",
    "Comfort Grip": "Wygodny chwyt",
    "Standard Stock": "Standardowa kolba",
    "Full Stock": "Pełna kolba",
    "Serrated Blade": "Ząbkowane ostrze",
    "Electrified Blade": "Naelektryzowane ostrze",
    "Stealth Blade": "Ukryte ostrze",
    "Curved Blade": "Zakrzywione ostrze",
    "Extended Blade": "Wydłużone ostrze",
    "Extra Flame Jets": "Dodatkowe dysze płomieni",
    "Heating Coil": "Cewka grzewcza",
    "Lead Lining": "Ołowiana okładzina",
    "Extra Claw": "Dodatkowy pazur",
    "Stun Pack": "Moduł ogłuszający",
    "Deep Dish": "Głęboka czasza",
    "Large Tank": "Duży zbiornik",
    "Huge Tank": "Ogromny zbiornik",
    "Triple Barrel": "Potrójna lufa",
    "Quad Barrel": "Poczwórna lufa",
    "Tri-Barrel": "Blok trzech luf",
    "Hair Trigger": "Czuły spust",
    "Sawed-Off": "Skrócona lufa",
    "Compensator": "Kompensator",
    "Suppressor": "Tłumik",
    "Bayonet": "Bagnet",
    "Stabilizer": "Stabilizator",
    "Hardened": "Hartowany",
    "Powerful": "Mocny",
    "Advanced": "Zaawansowany",
    "Calibrated": "Kalibrowany",
    "Automatic": "Automatyczny",
    "Snubnose": "Krótka lufa",
    "Ported": "Portowany",
    "Vented": "Wentylowany",
    "Finned": "Żebrowany",
    "Splitter": "Rozdzielacz",
    "Napalm": "Napalm",
    "Shredder": "Rozdrabniacz",
    "Scope": "Luneta",
    "Barbed": "Kolczasty",
    "Spiked": "Z kolcami",
    "Sharp": "Zaostrzony",
    "Chain-Wrapped": "Owiany łańcuchem",
    "Bladed": "Z ostrzem",
    "Puncturing": "Przebijający",
    "Extra Heavy": "Bardzo ciężki",
    "Heavy": "Ciężki",
    "Hooked": "Z hakiem",
    "Electrified": "Naelektryzowany",
  },
};

const EFFECT_TERMS = {
  ru: {
    "Aiming ignores cover and applies to the next attack during the scene": "Прицеливание игнорирует укрытие и действует на следующую атаку в этой сцене",
    "May re-roll hit location die": "Можно перебросить кубик зоны попадания",
    "Allows a Muzzle mod": "Позволяет установить дульную модификацию",
    "Adds a melee profile based on Fire Rate": "Добавляет профиль ближнего боя на основе скорострельности",
    "Melee profile: 4 damage, Piercing 1": "Профиль ближнего боя: урон 4, Пробивание 1",
    "on Sneak attacks": "при скрытных атаках",
    "may spend 2 AP to disarm": "можно потратить 2 ОД, чтобы обезоружить",
    "consumes": "расходует",
    "shots per attack": "зарядов за атаку",
    "increase Range by 1 step": "увеличивает дальность на 1 шаг",
    "reduce Range by 1 step": "уменьшает дальность на 1 шаг",
    "damage type becomes Energy": "тип урона становится энергетическим",
    "damage becomes": "урон становится",
    "ammo becomes": "боеприпас меняется на",
    "Fire Rate": "скорострельность",
    "damage": "урон",
    "Gain": "Добавляет",
    "gain": "добавляет",
    "Remove": "Убирает",
    "remove": "убирает",
    "Accurate": "Точное",
    "Night Vision": "Ночное видение",
    "Recon": "Разведка",
    "Vicious": "Жестокое",
    "Burst": "Очередь",
    "Inaccurate": "Неточное",
    "Reliable": "Надёжное",
    "Unreliable": "Ненадёжное",
    "Two-Handed": "Двуручное",
    "Close Quarters": "Ближний бой",
    "Suppressed": "Бесшумное",
    "Persistent": "Продолжительное",
    "Radioactive": "Радиоактивное",
    "Spread": "Разброс",
    "Blast": "Взрывное",
    "Piercing": "Пробивание",
    "Stun": "Оглушение",
    "Energy": "Энергия",
  },
  uk: {
    "Aiming ignores cover and applies to the next attack during the scene": "Прицілювання ігнорує укриття та діє на наступну атаку в цій сцені",
    "May re-roll hit location die": "Можна перекинути кубик зони влучання",
    "Allows a Muzzle mod": "Дозволяє встановити дульну модифікацію",
    "Adds a melee profile based on Fire Rate": "Додає профіль ближнього бою на основі скорострільності",
    "Melee profile: 4 damage, Piercing 1": "Профіль ближнього бою: шкода 4, Пробивання 1",
    "on Sneak attacks": "під час прихованих атак",
    "may spend 2 AP to disarm": "можна витратити 2 ОД, щоб обеззброїти",
    "consumes": "витрачає",
    "shots per attack": "зарядів за атаку",
    "increase Range by 1 step": "збільшує дальність на 1 крок",
    "reduce Range by 1 step": "зменшує дальність на 1 крок",
    "damage type becomes Energy": "тип шкоди стає енергетичним",
    "damage becomes": "шкода стає",
    "ammo becomes": "боєприпас змінюється на",
    "Fire Rate": "скорострільність",
    "damage": "шкода",
    "Gain": "Додає",
    "gain": "додає",
    "Remove": "Прибирає",
    "remove": "прибирає",
    "Accurate": "Точне",
    "Night Vision": "Нічне бачення",
    "Recon": "Розвідка",
    "Vicious": "Жорстоке",
    "Burst": "Черга",
    "Inaccurate": "Неточне",
    "Reliable": "Надійне",
    "Unreliable": "Ненадійне",
    "Two-Handed": "Дворучне",
    "Close Quarters": "Ближній бій",
    "Suppressed": "Безшумне",
    "Persistent": "Тривале",
    "Radioactive": "Радіоактивне",
    "Spread": "Розкид",
    "Blast": "Вибухове",
    "Piercing": "Пробивання",
    "Stun": "Оглушення",
    "Energy": "Енергія",
  },
  pl: {
    "Aiming ignores cover and applies to the next attack during the scene": "Celowanie ignoruje osłonę i działa na następny atak w tej scenie",
    "May re-roll hit location die": "Można przerzucić kość miejsca trafienia",
    "Allows a Muzzle mod": "Pozwala zamontować modyfikację wylotu lufy",
    "Adds a melee profile based on Fire Rate": "Dodaje profil walki wręcz zależny od szybkostrzelności",
    "Melee profile: 4 damage, Piercing 1": "Profil walki wręcz: 4 obrażenia, Przebicie 1",
    "on Sneak attacks": "podczas ataków z ukrycia",
    "may spend 2 AP to disarm": "można wydać 2 PA, aby rozbroić",
    "consumes": "zużywa",
    "shots per attack": "ładunków na atak",
    "increase Range by 1 step": "zwiększa zasięg o 1 poziom",
    "reduce Range by 1 step": "zmniejsza zasięg o 1 poziom",
    "damage type becomes Energy": "typ obrażeń zmienia się na energetyczny",
    "damage becomes": "obrażenia wynoszą",
    "ammo becomes": "amunicja zmienia się na",
    "Fire Rate": "szybkostrzelność",
    "damage": "obrażenia",
    "Gain": "Dodaje",
    "gain": "dodaje",
    "Remove": "Usuwa",
    "remove": "usuwa",
    "Accurate": "Celna",
    "Night Vision": "Noktowizja",
    "Recon": "Rozpoznanie",
    "Vicious": "Brutalna",
    "Burst": "Seria",
    "Inaccurate": "Niecelna",
    "Reliable": "Niezawodna",
    "Unreliable": "Zawodna",
    "Two-Handed": "Dwuręczna",
    "Close Quarters": "Walka w zwarciu",
    "Suppressed": "Wyciszona",
    "Persistent": "Trwałe",
    "Radioactive": "Radioaktywne",
    "Spread": "Rozrzut",
    "Blast": "Wybuchowa",
    "Piercing": "Przebicie",
    "Stun": "Ogłuszenie",
    "Energy": "Energia",
  },
};

const replaceTerms = (value, terms) => {
  let result = String(value || "");
  Object.entries(terms || {})
    .sort(([a], [b]) => b.length - a.length)
    .forEach(([source, target]) => {
      result = result.split(source).join(target);
    });
  return result;
};

const languageCode = (language) => String(language || "en").split("-")[0];

export function localizeWeaponModName(name, language) {
  const lang = languageCode(language);
  if (lang === "en") return name;
  return NAME_TERMS[lang]?.[name] || name;
}

export function localizeWeaponModEffect(effect, language) {
  const lang = languageCode(language);
  if (lang === "en") return effect;
  return replaceTerms(effect, EFFECT_TERMS[lang]);
}
