// Auto-generated perk asset map for Pip-2D20
export const PERK_ASSETS = {
  'Action Boy/Girl': '/assets/perks/action-boy-girl.png',
  'Adamantium Skeleton': '/assets/perks/adamantium-skeleton.png',
  'Adrenalin Rush': '/assets/perks/adrenalin-rush.png',
  'Animal Friend': '/assets/perks/animal-friend.png',
  'Aquaboy/Aquagirl': '/assets/perks/aquaboy-aquagirl.png',
  'Armorer': '/assets/perks/armorer.png',
  'Ammosmith': '/assets/perks/ammosmith.png',
  'Awareness': '/assets/perks/awareness.png',
  'Barbarian': '/assets/perks/barbarian.png',
  'Basher': '/assets/perks/basher.png',
  'Better Criticals': '/assets/perks/better-criticals.png',
  'Big Leagues': '/assets/perks/big-leagues.png',
  'Black Widow / Lady Killer': '/assets/perks/black-widow-lady-killer.png',
  'Blacksmith': '/assets/perks/blacksmith.png',
  'Blitz': '/assets/perks/blitz.png',
  'Bloody Mess': '/assets/perks/bloody-mess.png',
  'Can Do!': '/assets/perks/can-do.png',
  'Cap Collector': '/assets/perks/cap-collector.png',
  'Cautious Nature': '/assets/perks/cautious-nature.png',
  'Center Mass': '/assets/perks/center-mass.png',
  'Chem Resistant': '/assets/perks/chem-resistant.png',
  'Chemist': '/assets/perks/chemist.png',
  'Commando': '/assets/perks/commando.png',
  'Comprehension': '/assets/perks/comprehension.png',
  'Concentrated Fire': '/assets/perks/concentrated-fire.png',
  'Daring Nature': '/assets/perks/daring-nature.png',
  'Demolition Expert': '/assets/perks/demolition-expert.png',
  'Dodger': '/assets/perks/dodger.png',
  'Dogmeat': '/assets/perks/dogmeat.png',
  'Entomologist': '/assets/perks/entomologist.png',
  'Fast Metabolism': '/assets/perks/fast-metabolism.png',
  'Faster Healing': '/assets/perks/faster-healing.png',
  'Finesse': '/assets/perks/finesse.png',
  'Fortune Finder': '/assets/perks/fortune-finder.png',
  'Ghost': '/assets/perks/ghost.png',
  'Grim Reaper\'s Sprint': '/assets/perks/grim-reaper-s-sprint.png',
  'Gun Fu': '/assets/perks/gun-fu.png',
  'Gun Nut': '/assets/perks/gun-nut.png',
  'Gunslinger': '/assets/perks/gunslinger.png',
  'Hacker': '/assets/perks/hacker.png',
  'Healer': '/assets/perks/healer.png',
  'Heave Ho!': '/assets/perks/heave-ho.png',
  'Hunter': '/assets/perks/hunter.png',
  'Infiltrator': '/assets/perks/infiltrator.png',
  'Inspirational': '/assets/perks/inspirational.png',
  'Intense Training': '/assets/perks/intense-training.png',
  'Iron Fist': '/assets/perks/iron-fist.png',
  'Junktown Jerky Vendor': '/assets/perks/junktown-jerky-vendor.png',
  'Jury Rigging': '/assets/perks/jury-rigging.png',
  'Laser Commander': '/assets/perks/laser-commander.png',
  'Lead Belly': '/assets/perks/lead-belly.png',
  'Life Giver': '/assets/perks/life-giver.png',
  'Light Step': '/assets/perks/light-step.png',
  'Master Thief': '/assets/perks/master-thief.png',
  'Medic': '/assets/perks/medic.png',
  'Meltdown': '/assets/perks/meltdown.png',
  'Mister Sandman': '/assets/perks/mister-sandman.png',
  'Moving Target': '/assets/perks/moving-target.png',
  'Mysterious Stranger': '/assets/perks/mysterious-stranger.png',
  'Nerd Rage!': '/assets/perks/nerd-rage.png',
  'Night Person': '/assets/perks/night-person.png',
  'Ninja': '/assets/perks/ninja.png',
  'Nuclear Physicist': '/assets/perks/nuclear-physicist.png',
  'Pain Train': '/assets/perks/pain-train.png',
  'Paralyzing Palm': '/assets/perks/paralyzing-palm.png',
  'Party Boy/Girl': '/assets/perks/party-boy-girl.png',
  'Pathfinder': '/assets/perks/pathfinder.png',
  'Pharma Farma': '/assets/perks/pharma-farma.png',
  'Pickpocket': '/assets/perks/pickpocket.png',
  'Piercing Strike': '/assets/perks/piercing-strike.png',
  'Pyromaniac': '/assets/perks/pyromaniac.png',
  'Quick Draw': '/assets/perks/quick-draw.png',
  'Quick Hands': '/assets/perks/quick-hands.png',
  'Rad Resistance': '/assets/perks/rad-resistance.png',
  'Refractor': '/assets/perks/refractor.png',
  'Ricochet': '/assets/perks/ricochet.png',
  'Rifleman': '/assets/perks/rifleman.png',
  'Robotics Expert': '/assets/perks/robotics-expert.png',
  'Science!': '/assets/perks/science.png',
  'Scoundrel': '/assets/perks/scoundrel.png',
  'Scrapper': '/assets/perks/scrapper.png',
  'Scrounger': '/assets/perks/scrounger.png',
  'Shotgun Surgeon': '/assets/perks/shotgun-surgeon.png',
  'Size Matters': '/assets/perks/size-matters.png',
  'Skilled': '/assets/perks/skilled.png',
  'Slayer': '/assets/perks/slayer.png',
  'Smooth Talker': '/assets/perks/smooth-talker.png',
  'Snakeater': '/assets/perks/snakeater.png',
  'Sniper': '/assets/perks/sniper.png',
  'Solar Powered': '/assets/perks/solar-powered.png',
  'Steady Aim': '/assets/perks/steady-aim.png',
  'Strong Back': '/assets/perks/strong-back.png',
  'Tag!': '/assets/perks/tag.png',
  'Terrifying Presence': '/assets/perks/terrifying-presence.png',
  'Toughness': '/assets/perks/toughness.png',
  'All Night Long': '/assets/perks/all-night-long.png',
  'Bodyguards': '/assets/perks/bodyguards.png',
  'Community Organizer': '/assets/perks/community-organizer.png',
  'Contractor': '/assets/perks/contractor.png',
  'Covert Operator': '/assets/perks/covert-operator.png',
  'Enforcer': '/assets/perks/enforcer.png',
  'Green Thumb': '/assets/perks/green-thumb.png',
  'Gun Runner': '/assets/perks/gun-runner.png',
  'Happy Camper': '/assets/perks/happy-camper.png',
  'Hired Help': '/assets/perks/hired-help.png',
  'Home Defense': '/assets/perks/home-defense.png',
  'Homebody': '/assets/perks/homebody.png',
  'Local Leader': '/assets/perks/local-leader.png',
  'Mechanical Menace': '/assets/perks/mechanical-menace.png',
  'Class Freak': '/assets/perks/class-freak.png',
  'Nocturnal Fortitude': '/assets/perks/nocturnal-fortitude.png',
  'Pannapictagraphist': '/assets/perks/pannapictagraphist.png',
  'Pharmacist': '/assets/perks/pharmacist.png',
  'Photosynthetic': '/assets/perks/photosynthetic.png',
  'Quack Surgeon': '/assets/perks/quack-surgeon.png',
  'Rejuvenated': '/assets/perks/rejuvenated.png',
  'Retribution': '/assets/perks/retribution.png',
  'Robot Wrangler': '/assets/perks/robot-wrangler.png',
  'Squad Maneuvers': '/assets/perks/squad-maneuvers.png',
  'Super Duper': '/assets/perks/super-duper.png',
  'Taking One for the Team': '/assets/perks/taking-one-for-the-team.png',
  'Tinkerer': '/assets/perks/tinkerer.png',
  'True Friends': '/assets/perks/true-friends.png',
  'Blocker': '/assets/perks/blocker.png',
  'Bullet Shield': '/assets/perks/bullet-shield.png',
  'Gladiator': '/assets/perks/gladiator.png',
  'Incisor': '/assets/perks/incisor.png',
  'Lock and Load': '/assets/perks/lock-and-load.png',
  'Martial Artist': '/assets/perks/martial-artist.png',
  'Pack Rat': '/assets/perks/pack-rat.png',
  'Scattershot': '/assets/perks/scattershot.png',
  'Sturdy Frame': '/assets/perks/sturdy-frame.png',
  'Archer': '/assets/perks/archer.png',
  'Bow Before Me': '/assets/perks/bow-before-me.png',
  'Butcher\'s Bounty': '/assets/perks/butcher-s-bounty.png',
  'Crack Shot': '/assets/perks/crack-shot.png',
  'Fire in the Hole': '/assets/perks/fire-in-the-hole.png',
  'Glow Sight': '/assets/perks/glow-sight.png',
  'Night Eyes': '/assets/perks/night-eyes.png',
  'Cannibal': '/assets/perks/cannibal.png',
  'Cola Nut': '/assets/perks/cola-nut.png',
  'Dromedary': '/assets/perks/dromedary.png',
  'Fireproof': '/assets/perks/fireproof.png',
  'Ghoulish': '/assets/perks/ghoulish.png',
  'Ironclad': '/assets/perks/ironclad.png',
  'Natural Resistance': '/assets/perks/natural-resistance.png',
  'Radicool': '/assets/perks/radicool.png',
  'Revenant': '/assets/perks/revenant.png',
  'Slow Metabolizer': '/assets/perks/slow-metabolizer.png',
  'Thirst Quencher': '/assets/perks/thirst-quencher.png',
  'Vaccinated': '/assets/perks/vaccinated.png',
  'Bloodsucker': '/assets/perks/bloodsucker.png',
  'Responder': '/assets/perks/responder.png',
  'Field Surgeon': '/assets/perks/field-surgeon.png',
  'Happy Go Lucky': '/assets/perks/happy-go-lucky.png',
  'Healing Hands': '/assets/perks/healing-hands.png',
  'Overly Generous': '/assets/perks/overly-generous.png',
  'Spiritual Healer': '/assets/perks/spiritual-healer.png',
  'Suppressor': '/assets/perks/suppressor.png',
  'Tenderizer': '/assets/perks/tenderizer.png',
  'Licensed Plumber': '/assets/perks/licensed-plumber.png',
  'Power Patcher': '/assets/perks/power-patcher.png',
  'Power User': '/assets/perks/power-user.png',
  'Stabilized': '/assets/perks/stabilized.png',
  'Born Survivor': '/assets/perks/born-survivor.png',
  'Dead Man Sprinting': '/assets/perks/dead-man-sprinting.png',
  'Escape Artist': '/assets/perks/escape-artist.png',
  'Evasive': '/assets/perks/evasive.png',
  'Goat Legs': '/assets/perks/goat-legs.png',
  'Modern Renegade': '/assets/perks/modern-renegade.png',
  'Secret Agent': '/assets/perks/secret-agent.png',
  'Dry Nurse': '/assets/perks/dry-nurse.png',
  'Junk Shield': '/assets/perks/junk-shield.png',
  'Mysterious Savior': '/assets/perks/mysterious-savior.png',
  'Psychopath': '/assets/perks/psychopath.png',
  'Serendipity': '/assets/perks/serendipity.png',
  'Storm Chaser': '/assets/perks/storm-chaser.png',
};

export default PERK_ASSETS;
