const TEXT = {
  en: {
    world: "WORLD", overview: "OVERVIEW", local: "LOCAL", region: "REGION", enteredRegion: "REGION SELECTED", you: "YOU", destination: "DEST", direction: "DIR", steps: "STEPS", noRoute: "NO ROUTE", tapAnyCell: "TAP ANY CELL TO PLAN A ROUTE",
    route: "ROUTE", static: "STATIC", procedural: "PROCEDURAL", here: "HERE", noSafeRoute: "NO SAFE ROUTE", eta: "ETA", travelHint: "Travel follows the highlighted route and stops automatically if an encounter occurs.", startTravel: "START TRAVEL", routeUnavailable: "ROUTE UNAVAILABLE",
    worldOverview: "WORLD OVERVIEW", selectStaticLocation: "SELECT A STATIC LOCATION", fit: "FIT", target: "TARGET", blocks: "BLOCKS", sectorView: "SECTOR VIEW", currentPosition: "Current position",
    worldRouteStatic: "WORLD ROUTE // STATIC", sectors: "SECTORS", currentSector: "CURRENT SECTOR", km: "KM", youAreHere: "YOU ARE HERE", travelToTarget: "TRAVEL TO TARGET", worldRouteHint: "Auto route crosses sectors and stops if a random encounter interrupts the trip.",
    routeInterrupted: "ROUTE INTERRUPTED — encounter detected.", routeComplete: "ROUTE COMPLETE — {{steps}} steps, {{hours}}h.", worldRouteFailed: "WORLD ROUTE FAILED — no safe route to {{name}}.", worldRouteStart: "WORLD ROUTE // {{name}} // {{blocks}} blocks", enteredSector: "ENTERED SECTOR {{x}},{{y}}.", passed: "PASSED {{name}}.", worldRouteInterrupted: "WORLD ROUTE INTERRUPTED — encounter detected.", arrived: "ARRIVED // {{name}} // {{hours}}h.", worldRouteStopped: "WORLD ROUTE STOPPED before destination.", travelEncounter: "Travel encounter",
    autoGm: "AUTO GM", sessionArchive: "Session Archive", falloutSession: "Fallout 2D20 Session", saved: "SAVED", temp: "TEMP", visited: "VISITED", current: "CURRENT", newSession: "NEW SESSION", visitedStatic: "VISITED STATIC LOCATIONS", noSavedLocations: "No saved static locations yet.", messages: "messages", discoveries: "discoveries", character: "CHARACTER", notLoaded: "Not loaded", level: "LEVEL", location: "LOCATION", modeArchive: "MODE: ARCHIVE / READ ONLY", objective: "OBJECTIVE", exploreArea: "Explore area", discoveriesTitle: "DISCOVERIES", autoGmReady: "AUTO GM READY.", staticHistory: "This static location keeps its exploration history and discoveries.", proceduralTemp: "This procedural location is temporary and will reset after you leave.", processing: "AUTO GM IS PROCESSING...", archiveNote: "ARCHIVE VIEW — this journal is read-only. Return to CURRENT to continue playing at your character's actual WORLD position.", whatDo: "What do you do?", send: "SEND", unknownLocation: "Unknown location", wasteland: "Wasteland", gmEmpty: "The GM did not return a response.", gmError: "Could not contact Auto GM."
  },
  ru: {
    world: "МИР", overview: "ОБЗОР", local: "ЛОКАЛ", region: "РЕГИОН", enteredRegion: "РЕГИОН ВЫБРАН", you: "ВЫ", destination: "ЦЕЛЬ", direction: "НАПР", steps: "ШАГОВ", noRoute: "МАРШРУТА НЕТ", tapAnyCell: "НАЖМИТЕ НА КЛЕТКУ, ЧТОБЫ ПОСТРОИТЬ МАРШРУТ",
    route: "МАРШРУТ", static: "СТАТИЧЕСКАЯ", procedural: "СЛУЧАЙНАЯ", here: "ЗДЕСЬ", noSafeRoute: "БЕЗОПАСНОГО МАРШРУТА НЕТ", eta: "ВРЕМЯ", travelHint: "Путешествие идёт по выделенному маршруту и автоматически остановится при случайной встрече.", startTravel: "НАЧАТЬ ПУТЕШЕСТВИЕ", routeUnavailable: "МАРШРУТ НЕДОСТУПЕН",
    worldOverview: "ОБЗОР МИРА", selectStaticLocation: "ВЫБЕРИТЕ ЛОКАЦИЮ", fit: "ВПИСАТЬ", target: "ЦЕЛЬ", blocks: "БЛОКОВ", sectorView: "СЕКТОРОВ", currentPosition: "Текущая позиция",
    worldRouteStatic: "МИРОВОЙ МАРШРУТ // СТАТИЧЕСКАЯ", sectors: "СЕКТОРОВ", currentSector: "ТЕКУЩИЙ СЕКТОР", km: "КМ", youAreHere: "ВЫ ЗДЕСЬ", travelToTarget: "ИДТИ К ЦЕЛИ", worldRouteHint: "Автомаршрут проходит через сектора и останавливается, если путешествие прерывает случайная встреча.",
    routeInterrupted: "МАРШРУТ ПРЕРВАН — обнаружена случайная встреча.", routeComplete: "МАРШРУТ ЗАВЕРШЁН — {{steps}} шагов, {{hours}} ч.", worldRouteFailed: "НЕ УДАЛОСЬ ПОСТРОИТЬ МАРШРУТ к {{name}}.", worldRouteStart: "МИРОВОЙ МАРШРУТ // {{name}} // {{blocks}} блоков", enteredSector: "ВХОД В СЕКТОР {{x}},{{y}}.", passed: "ПРОЙДЕНО МИМО: {{name}}.", worldRouteInterrupted: "МИРОВОЙ МАРШРУТ ПРЕРВАН — случайная встреча.", arrived: "ПРИБЫТИЕ // {{name}} // {{hours}} ч.", worldRouteStopped: "МИРОВОЙ МАРШРУТ ОСТАНОВЛЕН до прибытия.", travelEncounter: "Случайная встреча",
    autoGm: "АВТО GM", sessionArchive: "Архив сессий", falloutSession: "Сессия Fallout 2D20", saved: "СОХРАНЕНО", temp: "ВРЕМЕННО", visited: "ПОСЕЩЁННЫЕ", current: "ТЕКУЩАЯ", newSession: "НОВАЯ СЕССИЯ", visitedStatic: "ПОСЕЩЁННЫЕ ПОСТОЯННЫЕ ЛОКАЦИИ", noSavedLocations: "Сохранённых локаций пока нет.", messages: "сообщений", discoveries: "открытий", character: "ПЕРСОНАЖ", notLoaded: "Не загружен", level: "УРОВЕНЬ", location: "ЛОКАЦИЯ", modeArchive: "РЕЖИМ: АРХИВ / ТОЛЬКО ЧТЕНИЕ", objective: "ЦЕЛЬ", exploreArea: "Исследовать местность", discoveriesTitle: "ОТКРЫТИЯ", autoGmReady: "АВТО GM ГОТОВ.", staticHistory: "Эта постоянная локация сохраняет историю исследования и открытия.", proceduralTemp: "Эта случайная локация временная и сбросится после ухода.", processing: "АВТО GM ОБРАБАТЫВАЕТ...", archiveNote: "АРХИВ — журнал доступен только для чтения. Вернитесь к ТЕКУЩЕЙ сессии, чтобы продолжить игру в фактической позиции персонажа.", whatDo: "Что вы делаете?", send: "ОТПРАВИТЬ", unknownLocation: "Неизвестная локация", wasteland: "Пустошь", gmEmpty: "GM не вернул ответ.", gmError: "Не удалось связаться с Авто GM."
  },
  uk: {
    world: "СВІТ", overview: "ОГЛЯД", local: "ЛОКАЛ", region: "РЕГІОН", enteredRegion: "РЕГІОН ОБРАНО", you: "ВИ", destination: "ЦІЛЬ", direction: "НАПР", steps: "КРОКІВ", noRoute: "МАРШРУТУ НЕМАЄ", tapAnyCell: "НАТИСНІТЬ НА КЛІТИНКУ, ЩОБ ПОБУДУВАТИ МАРШРУТ",
    route: "МАРШРУТ", static: "СТАТИЧНА", procedural: "ВИПАДКОВА", here: "ТУТ", noSafeRoute: "БЕЗПЕЧНОГО МАРШРУТУ НЕМАЄ", eta: "ЧАС", travelHint: "Подорож іде виділеним маршрутом і автоматично зупиниться при випадковій зустрічі.", startTravel: "ПОЧАТИ ПОДОРОЖ", routeUnavailable: "МАРШРУТ НЕДОСТУПНИЙ",
    worldOverview: "ОГЛЯД СВІТУ", selectStaticLocation: "ОБЕРІТЬ ЛОКАЦІЮ", fit: "ВМІСТИТИ", target: "ЦІЛЬ", blocks: "БЛОКІВ", sectorView: "СЕКТОРІВ", currentPosition: "Поточна позиція",
    worldRouteStatic: "СВІТОВИЙ МАРШРУТ // СТАТИЧНА", sectors: "СЕКТОРІВ", currentSector: "ПОТОЧНИЙ СЕКТОР", km: "КМ", youAreHere: "ВИ ТУТ", travelToTarget: "ЙТИ ДО ЦІЛІ", worldRouteHint: "Автомаршрут проходить крізь сектори та зупиняється, якщо подорож перериває випадкова зустріч.",
    routeInterrupted: "МАРШРУТ ПЕРЕРВАНО — виявлено випадкову зустріч.", routeComplete: "МАРШРУТ ЗАВЕРШЕНО — {{steps}} кроків, {{hours}} год.", worldRouteFailed: "НЕ ВДАЛОСЯ ПОБУДУВАТИ МАРШРУТ до {{name}}.", worldRouteStart: "СВІТОВИЙ МАРШРУТ // {{name}} // {{blocks}} блоків", enteredSector: "ВХІД У СЕКТОР {{x}},{{y}}.", passed: "ПРОЙДЕНО ПОВЗ: {{name}}.", worldRouteInterrupted: "СВІТОВИЙ МАРШРУТ ПЕРЕРВАНО — випадкова зустріч.", arrived: "ПРИБУТТЯ // {{name}} // {{hours}} год.", worldRouteStopped: "СВІТОВИЙ МАРШРУТ ЗУПИНЕНО до прибуття.", travelEncounter: "Випадкова зустріч",
    autoGm: "АВТО GM", sessionArchive: "Архів сесій", falloutSession: "Сесія Fallout 2D20", saved: "ЗБЕРЕЖЕНО", temp: "ТИМЧАСОВО", visited: "ВІДВІДАНІ", current: "ПОТОЧНА", newSession: "НОВА СЕСІЯ", visitedStatic: "ВІДВІДАНІ ПОСТІЙНІ ЛОКАЦІЇ", noSavedLocations: "Збережених локацій поки немає.", messages: "повідомлень", discoveries: "відкриттів", character: "ПЕРСОНАЖ", notLoaded: "Не завантажено", level: "РІВЕНЬ", location: "ЛОКАЦІЯ", modeArchive: "РЕЖИМ: АРХІВ / ЛИШЕ ЧИТАННЯ", objective: "ЦІЛЬ", exploreArea: "Дослідити місцевість", discoveriesTitle: "ВІДКРИТТЯ", autoGmReady: "АВТО GM ГОТОВИЙ.", staticHistory: "Ця постійна локація зберігає історію дослідження та відкриття.", proceduralTemp: "Ця випадкова локація тимчасова і скинеться після виходу.", processing: "АВТО GM ОБРОБЛЯЄ...", archiveNote: "АРХІВ — журнал доступний лише для читання. Поверніться до ПОТОЧНОЇ сесії, щоб продовжити гру у фактичній позиції персонажа.", whatDo: "Що ви робите?", send: "НАДІСЛАТИ", unknownLocation: "Невідома локація", wasteland: "Пустка", gmEmpty: "GM не повернув відповідь.", gmError: "Не вдалося зв'язатися з Авто GM."
  },
  pl: {
    world: "ŚWIAT", overview: "PRZEGLĄD", local: "LOKALNIE", region: "REGION", enteredRegion: "WYBRANO REGION", you: "TY", destination: "CEL", direction: "KIER", steps: "KROKÓW", noRoute: "BRAK TRASY", tapAnyCell: "DOTKNIJ POLA, ABY WYZNACZYĆ TRASĘ",
    route: "TRASA", static: "STAŁA", procedural: "LOSOWA", here: "TUTAJ", noSafeRoute: "BRAK BEZPIECZNEJ TRASY", eta: "CZAS", travelHint: "Podróż przebiega zaznaczoną trasą i automatycznie zatrzyma się przy losowym spotkaniu.", startTravel: "ROZPOCZNIJ PODRÓŻ", routeUnavailable: "TRASA NIEDOSTĘPNA",
    worldOverview: "PRZEGLĄD ŚWIATA", selectStaticLocation: "WYBIERZ LOKACJĘ", fit: "DOPASUJ", target: "CEL", blocks: "BLOKÓW", sectorView: "SEKTORÓW", currentPosition: "Aktualna pozycja",
    worldRouteStatic: "TRASA ŚWIATOWA // STAŁA", sectors: "SEKTORÓW", currentSector: "BIEŻĄCY SEKTOR", km: "KM", youAreHere: "JESTEŚ TUTAJ", travelToTarget: "IDŹ DO CELU", worldRouteHint: "Automatyczna trasa przechodzi przez sektory i zatrzymuje się, jeśli podróż przerwie losowe spotkanie.",
    routeInterrupted: "TRASA PRZERWANA — wykryto losowe spotkanie.", routeComplete: "TRASA UKOŃCZONA — {{steps}} kroków, {{hours}} godz.", worldRouteFailed: "NIE UDAŁO SIĘ WYZNACZYĆ TRASY do {{name}}.", worldRouteStart: "TRASA ŚWIATOWA // {{name}} // {{blocks}} bloków", enteredSector: "WEJŚCIE DO SEKTORA {{x}},{{y}}.", passed: "MINIĘTO: {{name}}.", worldRouteInterrupted: "TRASA ŚWIATOWA PRZERWANA — losowe spotkanie.", arrived: "PRZYBYCIE // {{name}} // {{hours}} godz.", worldRouteStopped: "TRASA ŚWIATOWA ZATRZYMANA przed celem.", travelEncounter: "Losowe spotkanie",
    autoGm: "AUTO GM", sessionArchive: "Archiwum sesji", falloutSession: "Sesja Fallout 2D20", saved: "ZAPISANO", temp: "TYMCZASOWA", visited: "ODWIEDZONE", current: "BIEŻĄCA", newSession: "NOWA SESJA", visitedStatic: "ODWIEDZONE STAŁE LOKACJE", noSavedLocations: "Brak zapisanych lokacji.", messages: "wiadomości", discoveries: "odkryć", character: "POSTAĆ", notLoaded: "Nie wczytano", level: "POZIOM", location: "LOKACJA", modeArchive: "TRYB: ARCHIWUM / TYLKO ODCZYT", objective: "CEL", exploreArea: "Zbadaj okolicę", discoveriesTitle: "ODKRYCIA", autoGmReady: "AUTO GM GOTOWY.", staticHistory: "Ta stała lokacja zachowuje historię eksploracji i odkrycia.", proceduralTemp: "Ta losowa lokacja jest tymczasowa i zresetuje się po wyjściu.", processing: "AUTO GM PRZETWARZA...", archiveNote: "ARCHIWUM — dziennik jest tylko do odczytu. Wróć do BIEŻĄCEJ sesji, aby kontynuować grę w aktualnej pozycji postaci.", whatDo: "Co robisz?", send: "WYŚLIJ", unknownLocation: "Nieznana lokacja", wasteland: "Pustkowia", gmEmpty: "GM nie zwrócił odpowiedzi.", gmError: "Nie udało się połączyć z Auto GM."
  }
};

function languageCode(language) {
  const code = String(language || "en").toLowerCase().split("-")[0];
  return TEXT[code] ? code : "en";
}

export function mapUiText(language, key, vars = {}) {
  const code = languageCode(language);
  let value = TEXT[code]?.[key] ?? TEXT.en[key] ?? key;
  for (const [name, replacement] of Object.entries(vars)) {
    value = String(value).replaceAll(`{{${name}}}`, String(replacement));
  }
  return value;
}

export function getMapLanguageCode(language) {
  return languageCode(language);
}
